# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Astroknit
tagline:          'John Diggins'
description:      'Discussions of yarn and music'
url:              http://jdiggins.com
baseurl:          /

author:
  name:           'John Diggins'
  url:            https://twitter.com/astroknit

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
